### ISSUE TITLE
代码中 设置view的背景

### ISSUE THREAD

**Issue by D-zy** [zhaoxuyang/chameleon#2]
博主,换肤 时 ,请教下如何代码里设置某个view的颜色,比如main_bg 的属性,

**Comment by D-zy** [comment]
按照了文档 代码设置无效,

**Comment by zhaoxuyang** [comment]
> 按照了文档 代码设置无效,



> 博主,换肤 时 ,




> 博主,换肤 时 ,请教下如何代码里设置某个view的颜色,比如main_bg 的属性,

此功能在开发中
