### ISSUE TITLE
设置了无效 ,只是显示初始化的颜色

### ISSUE THREAD

**Issue by D-zy** [zhaoxuyang/chameleon#3]
设置了无效 ,只是显示初始化的颜色

**Comment by bing27** [comment]
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:color="?attr/skin_tv" android:state_pressed="true" />
    <item android:color="?attr/skin_tv" android:state_checked="true" />
    <item android:color="#8a8a8a" />
</selector>

**Comment by bing27** [comment]
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:color="?attr/skin_tv" android:state_pressed="true" />
    <item android:color="?attr/skin_tv" android:state_checked="true" />
    <item android:color="#8a8a8a" />
</selector>
