### ISSUE TITLE
存在内存泄露问题

### ISSUE THREAD

**Issue by D-zy** [zhaoxuyang/chameleon#5]
hi,博主,我用第三方的内存泄露检测到,换肤后,存在内存泄露问题
![4621dbc419a5c4f314d98ebcec249cf](https://user-images.githubusercontent.com/23740845/54110613-cbc57800-441c-11e9-8b90-093629c5d2ff.jpg)

**Comment by zhaoxuyang** [comment]
> hi,博主,我用第三方的内存泄露检测到,换肤后,存在内存泄露问题
> ![4621dbc419a5c4f314d98ebcec249cf](https://user-images.githubusercontent.com/23740845/54110613-cbc57800-441c-11e9-8b90-093629c5d2ff.jpg)

请参考最新的接入文档，已经去除弱引用来管理observer了
