### ISSUE TITLE
使用框架后，所有的ImageView都失踪了

### ISSUE THREAD

**Issue by AndyLeeBlue** [zhaoxuyang/chameleon#7]

**Comment by zhaoxuyang** [comment]
能详细描述下么，令请更新下最新代码

**Comment by AndyLeeBlue** [comment]
随便任何地方，放一个ImageView，运行下就看不到了，最新版本还没来及测试

AndroidX，环境是8.0系统，华为10，去除换肤框架，图片正常显示

**Comment by AndyLeeBlue** [comment]
换了最新版本，还是不能显示，是用在fragment中的

**Comment by AndyLeeBlue** [comment]
找到原因了，我工程中的ImageView的均使用app:srcCompat方式引入图片，换成android:src在换肤框架下就能正常显示了。但是app:srcCompat方式是大势所趋，楼主能修改下支持app:srcCompat方式吗？

xml中用android.support.v7.widget.AppCompatImageView也可以使用app:srcCompat，但是工程是AndroidX的，还是不妥。

**Comment by zhaoxuyang** [comment]
> 找到原因了，我工程中的ImageView的均使用app:srcCompat方式引入图片，换成android:src在换肤框架下就能正常显示了。但是app:srcCompat方式是大势所趋，楼主能修改下支持app:srcCompat方式吗？
> 
> xml中用android.support.v7.widget.AppCompatImageView也可以使用app:srcCompat，但是工程是AndroidX的，还是不妥。

你好，修改后的代码已提交，请参考最新的接入文档
